### ISSUE TITLE
code  formating

### ISSUE THREAD

**Issue by Ngufor-emmanuella** [Nejjari001/Portfolio-setup-and-mobile-firs#11]
Nice work done your project is perfect everything is complete but i think you need to give spacing to your html codes for good presentation and it makes your work clean

**Comment by kennankole** [comment]
Yes, code formatting makes your code presentable. 
You could try the code with the commands below from your Visual Studio Code editor through the following shortcuts:

- [ ] On Windows Shift + Alt + F
- [ ] On Linux Ctrl + Shift + I
